CREATE DATABASE InLock_Games_Tarde

USE InLock_Games_Tarde

CREATE TABLE ESTUDIOS (
	ESTUDIOID INT IDENTITY PRIMARY KEY
	,NOMEESTUDIO VARCHAR(150) NOT NULL
);

CREATE TABLE JOGOS (
	JOGOID INT IDENTITY PRIMARY KEY
	,NOMEJOGO VARCHAR(150) NOT NULL
	,DESCRICAO VARCHAR(150) NOT NULL
	,DATALANCAMENTO DATETIME NOT NULL
	,VALOR DECIMAL (10,2)
	,ID_ESTUDIOS INT FOREIGN KEY REFERENCES ESTUDIOS(ESTUDIOID) NOT NULL
);

CREATE TABLE USUARIOS (
	USUARIOID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(150) NOT NULL
	,SENHA VARCHAR(150) NOT NULL
	,TIPOUSUARIO VARCHAR(150) NOT NULL UNIQUE
);

DROP TABLE USUARIOS

select * from jogos;

SELECT * FROM USUARIOS