SELECT COUNT (*) FROM USUARIOS

SELECT COUNT (*) FROM ESTUDIOS

SELECT COUNT (*) FROM JOGOS

SELECT COUNT(*) FROM JOGOS WHERE ESTUDIOS;

SELECT * FROM JOGOS INNER JOIN ESTUDIOS ON ESTUDIOS.NOMEESTUDIO = NOMEESTUDIO

SELECT * FROM ESTUDIOS

